const id = document.getElementById("video")
const btnAlegria = document.getElementById("btnAlegria")
const btnRaiva = document.getElementById("btnRaiva")
const btnMedo = document.getElementById("btnMedo")
const btnTristeza = document.getElementById("btnTristeza")
const btnNojo = document.getElementById("btnNojo")
const btnInveja = document.getElementById("btnInveja")
const btnVergonha = document.getElementById("btnVergonha")
const btnAnsiedade = document.getElementById("btnAnsiedade")
const btnTedio = document.getElementById("btnTedio")

btnAlegria.addEventListener("click", () => video.src = "alegria.mp4")
btnRaiva.addEventListener("click", () => video.src = "raiva.mp4")
btnMedo.addEventListener("click", () => video.src = "medo.mp4")
btnTristeza.addEventListener("click", () => video.src = "tristeza.mp4")
btnNojo.addEventListener("click", () => video.src = "nojo.mp4")
btnInveja.addEventListener("click", () => video.src = "inveja.mp4")
btnVergonha.addEventListener("click", () => video.src = "vergonha.mp4")
btnAnsiedade.addEventListener("click", () => video.src = "ansiedade.mp4")
btnTedio.addEventListener("click", () => video.src = "tedio.mp4")